/**
 * This file has been autogenerated as it didn't exist or was made for an older incompatible version.
 * This file can be used for manual configuration will not be modified if the flowDefaults constant exists.
 */
const merge = require("webpack-merge");
const flowDefaults = require("./webpack.generated.js");
const themeFolder = require("path").resolve(
  __dirname,
  "src/main/resources/META-INF/resources/theme"
);

module.exports = merge(flowDefaults, {
  resolve: {
    alias: {
      Theme: themeFolder,
    },
  },
});
